ProjectPlanner/Models/Todo.cs
using ProjectPlanner.CustomValidations;
using System;
using System.ComponentModel.DataAnnotations;

namespace ProjectPlanner.Models
{
    public class Todo
    {
        public int TodoId { get; set; }
        public int ProjectId { get; set; }

        public Project Project { get; set; }

        [Required(ErrorMessage = "Name is required.")]
        [StringLength(30, MinimumLength = 5, ErrorMessage = "The name must be between 5 and 30 characters.")]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Description is required.")]
        [StringLength(200, MinimumLength = 10, ErrorMessage = "The description must be between 10 and 200 characters.")]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [DisplayFormat(DataFormatString = "{0:dddd dd MMM yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public DateTime CreatedDate { get; set; }

        [FutureDateAttribute]
        [DisplayFormat(DataFormatString = "{0:dddd dd MMM yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        [Display(Name = "Estimated Date")]
        public DateTime EstimatedDate { get; set; }

        public string Status { get; set; }
    }
}

ProjectPlanner/ViewModels/TodoViewModel.cs
using ProjectPlanner.Models;

namespace ProjectPlanner.ViewModels
{
    public class TodoViewModel
    {
        public Todo Todo { get; set; }

        public int ProjectId { get; set; }
    }
}

ProjectPlanner/Controllers/TodosController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectPlanner.Data;
using ProjectPlanner.Models;
using ProjectPlanner.ViewModels;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectPlanner.Controllers
{

    public class TodosController : Controller
    {
        private readonly ITodoRepository _todoRepository;
        private readonly IProjectRepository _projectRepository;

        public TodosController(ITodoRepository todoRepository, IProjectRepository projectRepository)
        {
            _todoRepository = todoRepository;
            _projectRepository = projectRepository;
        }

        // GET: Todos
        [Route("projects/{projectId:int}/todos")]
        public async Task<IActionResult> Index([FromRoute]int projectId, string searchString)
        {
            var todos = await _todoRepository.AllTodosByProjectId(projectId).ConfigureAwait(true);
            var project = await _todoRepository.GetProjectById(projectId).ConfigureAwait(true);

            if (!string.IsNullOrEmpty(searchString))
            {
                searchString.ToLower();

                todos = todos.Where(t => t.Name.ToLower().Contains(searchString)).ToList();
            }

            var model = new TodoListViewModel
            {
                Todos = todos,
                Project = project
            };

            return View(model);
        }

        //// GET: todos/create
        [HttpGet]
        [Route("projects/{projectId:int}/todos/create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("projects/{projectId:int}/todos/create")]
        public async Task<IActionResult> Create([Bind("Name,Description,EstimatedDate")] Todo todo, int projectId)
        {
            if (ModelState.IsValid)
            {
                await _todoRepository.CreateTodo(projectId, todo).ConfigureAwait(true);
                await _projectRepository.CalculateCompletion(projectId).ConfigureAwait(true);
            }
            return RedirectToRoute("todos", new { id = projectId });
        }

        //// GET: todos/todoId/edit
        [Route("projects/{projectId:int}/todos/{todoId:int}/edit")]
        public async Task<IActionResult> Edit(int projectId, int todoId)
        {
            if (todoId == 0)
            {
                return NotFound();
            }

            var todo = await _todoRepository.GetTodoById(todoId).ConfigureAwait(true);

            var model = new TodoViewModel
            {
                ProjectId = projectId,
                Todo = todo
            };

            return View(model);
        }

        //// POST: todos/todosId/edit
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("projects/{projectId:int}/todos/{todoId:int}/edit")]

        public async Task<IActionResult> Edit(int projectId, int todoId, [Bind("Name, Description, EstimatedDate")] Todo todo)
        {
            if (todoId == 0 || projectId == 0 || todo == null)
            {
                return RedirectToAction("Index", "Projects");
            }

            if (ModelState.IsValid)
            {
                todo.TodoId = todoId;
                await _todoRepository.UpdateTodo(todo).ConfigureAwait(true);
            }

            return RedirectToRoute("todos", new { id = projectId });
        }

        //// GET: projects/id/delete
        [Route("projects/{projectId:int}/todos/{todoId:int}/delete")]
        public async Task<IActionResult> Delete(int todoId)
        {
            if (todoId == 0)
            {
                return NotFound();
            }

            var todo = await _todoRepository.GetTodoById(todoId).ConfigureAwait(true);

            if (todo == null)
            {
                return RedirectToRoute("todos", new { id = todo.Project.ProjectId });
            }


            return View(todo);
        }

        //// POST: projects/projectId/delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Route("projects/{projectId:int}/todos/{todoId:int}/delete")]
        public async Task<IActionResult> DeleteConfirmed(int projectId, int todoId)
        {
            await _todoRepository.DeleteTodo(todoId).ConfigureAwait(true);

            await _projectRepository.CalculateCompletion(projectId).ConfigureAwait(true);

            return RedirectToRoute("todos", new { id = projectId });
        }


        [Route("projects/{projectId:int}/todos/{todoId:int}/status")]
        public async Task<IActionResult> ChangeStatus(int todoId, int projectId, string status)
        {
            await _todoRepository.ChangeTodoStatus(todoId, status).ConfigureAwait(true);

            await _projectRepository.CalculateCompletion(projectId).ConfigureAwait(true);

            return RedirectToRoute("todos", new { id = projectId });
        }

    }
}

ProjectPlanner/Views/Todos/Create.cshtml
@model ProjectPlanner.Models.Todo

@{
    ViewData["Title"] = "Create";
}


<link rel="stylesheet" href="~/css/projects.css" type="text/css" />
<link rel="stylesheet" href="~/css/datePicker.css" type="text/css" />
<link rel="stylesheet" href="~/css/projectForms.css" type="text/css" />

<div class="form-panel ">
    <div class="form-header">
        <h1>Create new Task</h1>
    </div>
    <div class="form-content">
        <form asp-controller="Todos" asp-action="Create">
            <div class="form-group">
                <label asp-for="Name" class="control-label "></label>
                <input asp-for="Name" class="form-control" autocomplete="off" />
            </div>
            <div class="text-center">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label "></label>
                <textarea asp-for="Description" class="form-control" autocomplete="off"></textarea>
            </div>
            <div class="text-center">
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstimatedDate" class=" control-label"></label>
                <div class="input-group">
                    <span class="input-group-prepend input-group-text"><i class="fas fa-calendar-alt"></i>  </span>
                    <input asp-for="EstimatedDate" type="text" class="form-control datepicker" autocomplete="off" readonly>
                </div>
            </div>
            <div class="text-center mb-1">
                <span asp-validation-for="EstimatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="create">Create</button>
            </div>
            <div class="form-group text-right">
                <a asp-action="Index"><i class="fa fa-arrow-left fa-xs"></i> Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript" src="~/js/datepicker.js"></script>

}

ProjectPlanner/Views/Todos/Delete.cshtml
@model ProjectPlanner.Models.Todo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Todo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstimatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstimatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TodoId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ProjectPlanner/Views/Todos/Edit.cshtml
@model ProjectPlanner.ViewModels.TodoViewModel

@{
    ViewData["Title"] = "Edit";
}

<link rel="stylesheet" href="~/css/projects.css" type="text/css" />
<link rel="stylesheet" href="~/css/datePicker.css" type="text/css" />
<link rel="stylesheet" href="~/css/projectForms.css" type="text/css" />

<div class="form-panel ">
    <div class="form-header">
        <h1>Edit Task</h1>
    </div>
    <div class="form-content">
        <form asp-controller="Todos" asp-action="Edit" asp-route-todoId="@Model.Todo.TodoId" asp-route-projectId="@Model.ProjectId">
            <div class="form-group">
                <label asp-for="@Model.Todo.Name" class="control-label "></label>
                <input asp-for="@Model.Todo.Name" class="form-control" autocomplete="off" />
            </div>
            <div class="text-center">
                <span asp-validation-for="@Model.Todo.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Todo.Description" class="control-label "></label>
                <textarea asp-for="@Model.Todo.Description" class="form-control" autocomplete="off"></textarea>
            </div>
            <div class="text-center">
                <span asp-validation-for="@Model.Todo.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Todo.EstimatedDate" class=" control-label"></label>
                <div class="input-group">
                    <span class="input-group-prepend input-group-text"><i class="fas fa-calendar-alt"></i>  </span>
                    <input asp-for="@Model.Todo.EstimatedDate" type="text" class="form-control datepicker" autocomplete="off" readonly>
                </div>
            </div>
            <div class="text-center mb-1">
                <span asp-validation-for="@Model.Todo.EstimatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="create">Save</button>
            </div>
            <div class="form-group text-right">
                <a asp-action="Index"><i class="fa fa-arrow-left fa-xs"></i> Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript" src="~/js/datepicker.js"></script>

}

ProjectPlanner/Views/Todos/Index.cshtml
@model ProjectPlanner.ViewModels.TodoListViewModel

@{
    ViewData["Title"] = "Index";
}

<link rel="Stylesheet" href="~/css/projects.css" type="text/css" />

<ul class="list-group">
    <li class="col-sm-12 col-md-12 ">
        <div class="container mt-3">
            <div class="d-flex justify-content-center h-100">
                <form class="searchbar" asp-controller="Todos" asp-action="Index">
                    <input class="search_input" type="text" name="searchString" placeholder="Name..." autocomplete="off">
                    <button class="search_icon" type="submit"><i class="fas fa-search"></i></button>
                </form>
            </div>
        </div>
    </li>
    <li class="col-sm-12 col-md-12">
        <div class="row">
            <div class="col-sm-6 col-md-6 projectTitle">
                <h1>@Model.Project.Name</h1>
            </div>
            <div class="col-sm-6 col-md-6 text-right">
                <a asp-controller="Todos" asp-action="Create" asp-route-projectId="@Model.Project.ProjectId"
                   class="btn newProject mt-3 mb-3">New Todo</a>
            </div>
        </div>
    </li>

    @foreach (var todo in Model.Todos)
    {
        var style = "";

        if (todo.Status == "Completed") style = "color: green";
        else if (todo.Status == "In progress") style = "color: grey";
        else style = "color: red";

        <li class="col-sm-12 col-md-12">
            <div class="card text-center projectItem">
                <div class="card-header">
                    <h5 class="card-title">@todo.Name</h5>
                    <span class="status">Status: <span style="@style">@todo.Status</span></span>
                </div>
                <div class="card-body">
                    <p class="card-text text-left">@todo.Description</p>
                </div>
                <div class="card-footer row p-0">
                    <div class="col-sm-3 col-md-6 col-xs-3 text-left ">
                        <div class="dropdown">
                            <a class="btn btnStatus " href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Change Status <i class="fas fa-caret-down"></i>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item"
                                   asp-controller="Todos" asp-action="ChangeStatus" asp-route-status="Pending" asp-route-projectId="@Model.Project.ProjectId" asp-route-todoId="@todo.TodoId">Pending</a>
                                <a class="dropdown-item"
                                   asp-controller="Todos" asp-action="ChangeStatus" asp-route-status="In progress" asp-route-projectId="@Model.Project.ProjectId" asp-route-todoId="@todo.TodoId">In progress</a>
                                <a class="dropdown-item"
                                   asp-controller="Todos" asp-action="ChangeStatus" asp-route-status="Completed" asp-route-projectId="@Model.Project.ProjectId" asp-route-todoId="@todo.TodoId">Completed</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3 col-md-6 col-xs-3 text-right ">
                        <a class="btn btn-warning text-white btnProject"
                           asp-controller="Todos" asp-action="Edit" asp-route-projectId="@Model.Project.ProjectId" asp-route-todoId="@todo.TodoId">
                            Edit <i class="fas fa-edit"></i>
                        </a>
                        <a class="btn btn-danger btnProject"
                           asp-controller="Todos" asp-action="Delete" asp-route-projectId="@Model.Project.ProjectId" asp-route-todoId="@todo.TodoId">
                            Delete <i class="fas fa-trash"></i>
                        </a>
                    </div>
                </div>
            </div>
        </li>

    }

</ul>

<script>
    $('.dropdown').on('show.bs.dropdown', function () {
        $(this).find('.dropdown-menu').first().stop(true, true).slideDown(300);
    });

    // Add slideUp animation to dropdown
    $('.dropdown').on('hide.bs.dropdown', function () {
        $(this).find('.dropdown-menu').first().stop(true, true).slideUp(300);
    });

</script>