ProjectPlanner/Models/Project.cs
using ProjectPlanner.CustomValidations;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ProjectPlanner.Models
{
    public class Project
    {
        public int ProjectId { get; set; }


        public string UserId { get; set; }
        public User User { get; set; }

        [Required(ErrorMessage = "Name is required.")]
        [StringLength(30, MinimumLength = 5, ErrorMessage = "The name must be between 5 and 30 characters.")]
        [Display(Name = "Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Description is required.")]
        [StringLength(200, MinimumLength = 10, ErrorMessage = "The description must be between 10 and 200 characters.")]
        [Display(Name = "Description")]
        public string Description { get; set; }
        [DisplayFormat(DataFormatString = "{0:dddd dd MMM yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public DateTime CreatedDate { get; set; }

        [FutureDateAttribute]
        [DisplayFormat(DataFormatString = "{0:dddd dd MMM yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        [Display(Name = "Estimated Date")]
        public DateTime EstimatedDate { get; set; }
        public List<Todo> Todos { get;  } = new List<Todo>();

        public decimal PercentageOfCompletion { get; set; }
    }
}

ProjectPlanner/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProjectPlanner.Data;
using ProjectPlanner.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectPlanner.Controllers
{
    [Route("projects")]
    [Authorize]
    public class ProjectsController : Controller
    {
        private readonly IProjectRepository _projectRepository;
        private readonly UserManager<User> _userManager;

        public ProjectsController(IProjectRepository projectRepository, UserManager<User> userManager)
        {
            _projectRepository = projectRepository;
            _userManager = userManager;
        }

        //// GET: Projects

        public async Task<IActionResult> Index(string searchString)
        {
            //var projects = _projectRepository.AllProjects.ToList();

            var user = await _userManager.GetUserAsync(HttpContext.User).ConfigureAwait(true);

            if (user == null)
            {
                return NotFound();
            }

            var projects = _projectRepository.GetAllProjects(user).ToList();

            if (!string.IsNullOrEmpty(searchString))
            {
                searchString.ToLower();

                projects = projects.Where(p => p.Name.ToLower().Contains(searchString)).ToList();
            }
            return View(projects);
        }

        //// GET: projects/create
        [Route("create")]
        public IActionResult Create()
        {
            return View();
        }

        //// POST: projects/create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        ///
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("create")]
        public async Task<IActionResult> Create([Bind("Name,Description,EstimatedDate")] Project project)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(HttpContext.User).ConfigureAwait(true);

                if (user == null)
                {
                    return RedirectToAction("Login", "Account");
                }

                try
                {
                    await _projectRepository.CreateProject(project, user).ConfigureAwait(true);
                }
                catch (ArgumentNullException)
                {

                    return RedirectToAction(nameof(Index));
                }
            }
            return RedirectToAction(nameof(Index));
        }

        //// GET: projects/id/edit
        [Route("projectId:int/edit")]
        public async Task<IActionResult> Edit(int projectId)
        {
            if (projectId == 0)
            {
                return NotFound();
            }

            var project = await _projectRepository.GetProjectById(projectId).ConfigureAwait(true);

            return View(project);
        }

        //// POST: projects/projectId/edit
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("projectId:int/edit")]

        public async Task<IActionResult> Edit(int projectId, [Bind("Name, Description, EstimatedDate")] Project project)
        {
            if (project == null || projectId == 0)
            {
                return RedirectToAction(nameof(Index));
            }

            if (ModelState.IsValid)
            {
                project.ProjectId = projectId;
                await _projectRepository.UpdateProject(project).ConfigureAwait(true);
            }

            return RedirectToAction(nameof(Index));
        }

        //// GET: projects/id/delete
        [Route("projectId:int/delete")]
        public async Task<IActionResult> Delete(int projectId)
        {
            if (projectId == 0)
            {
                return RedirectToAction(nameof(Index));
            }

            var project = await _projectRepository.GetProjectById(projectId).ConfigureAwait(true);

            if (project == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(project);
        }

        //// POST: projects/projectId/delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Route("projectId:int/delete")]
        public async Task<IActionResult> DeleteConfirmed(int projectId)
        {
            await _projectRepository.DeleteProject(projectId).ConfigureAwait(true);

            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> ProjectExists(int projectId)
        {
            return await _projectRepository.ProjectExists(projectId).ConfigureAwait(true);
        }


    }
}

ProjectPlanner/Views/Projects/Create.cshtml
@model ProjectPlanner.Models.Project

@{
    ViewData["Title"] = "Create";
}

<link rel="stylesheet" href="~/css/projects.css" type="text/css" />
<link rel="stylesheet" href="~/css/datePicker.css" type="text/css" />
<link rel="stylesheet" href="~/css/projectForms.css" type="text/css" />

<div class="form-panel ">
    <div class="form-header">
        <h1>Create new project</h1>
    </div>
    <div class="form-content">
        <form asp-controller="Projects" asp-action="Create">
            <div class="form-group">
                <label asp-for="Name" class="control-label "></label>
                <input asp-for="Name" class="form-control" autocomplete="off" />
            </div>
            <div class="text-center">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label "></label>
                <textarea asp-for="Description" class="form-control" autocomplete="off"></textarea>
            </div>
            <div class="text-center">
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstimatedDate" class=" control-label"></label>
                <div class="input-group">
                    <span class="input-group-prepend input-group-text"><i class="fas fa-calendar-alt"></i>  </span>
                    <input asp-for="EstimatedDate" type="text" class="form-control datepicker" autocomplete="off" readonly>
                </div>
            </div>
            <div class="text-center mb-1">
                <span asp-validation-for="EstimatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="create">Create</button>
            </div>
            <div class="form-group text-right">
                <a asp-action="Index"><i class="fa fa-arrow-left fa-xs"></i> Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript" src="~/js/datepicker.js"></script>

}

ProjectPlanner/Views/Projects/Delete.cshtml
@model ProjectPlanner.Models.Project

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstimatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstimatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProjectId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ProjectPlanner/Views/Projects/Edit.cshtml
@model Project

@{
    ViewData["Title"] = "Edit";
}

<link rel="stylesheet" href="~/css/projects.css" type="text/css" />
<link rel="stylesheet" href="~/css/datePicker.css" type="text/css" />
<link rel="stylesheet" href="~/css/projectForms.css" type="text/css" />

<div class="form-panel ">
    <div class="form-header">
        <h1>Create new project</h1>
    </div>
    <div class="form-content">
        <form asp-controller="Projects" asp-action="Edit" asp-route-projectId="@Model.ProjectId">
            <div class="form-group">
                <label asp-for="Name" class="control-label "></label>
                <input asp-for="Name" class="form-control" autocomplete="off" />
            </div>
            <div class="text-center">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label "></label>
                <textarea asp-for="Description" class="form-control" autocomplete="off"></textarea>
            </div>
            <div class="text-center">
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstimatedDate" class=" control-label"></label>
                <div class="input-group">
                    <span class="input-group-prepend input-group-text"><i class="fas fa-calendar-alt"></i>  </span>
                    <input asp-for="EstimatedDate" type="text" class="form-control datepicker" autocomplete="off" readonly>
                </div>
            </div>
            <div class="text-center mb-1">
                <span asp-validation-for="EstimatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="create">Save</button>
            </div>
            <div class="form-group text-right">
                <a asp-action="Index"><i class="fa fa-arrow-left fa-xs"></i> Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript" src="~/js/datepicker.js"></script>
}

ProjectPlanner/Views/Projects/Index.cshtml
@model IEnumerable<Project>

@{
    ViewData["Title"] = "Index";
}
<link rel="Stylesheet" href="~/css/projects.css" type="text/css" />



<ul class="list-group row">
    @if (Model.Any())
    {
        <li class="col-sm-12 col-md-12 ">
            <div class="container mt-3">
                <div class="d-flex justify-content-center h-100">
                    <form class="searchbar" asp-controller="Projects" asp-action="Index">
                        <input class="search_input" type="text" name="searchString" placeholder="Name..." autocomplete="off">
                        <button class="search_icon" type="submit"><i class="fas fa-search"></i></button>
                    </form>
                </div>
            </div>
        </li>
    }
    else
    {
        <li class="col-12 text-center mt-3">
            <h3 class="project-page-title"> You have no projects in your repository.</h3>
        </li>
    }
    <li class="col-sm-12 col-md-12 text-right">
        <a asp-controller="Projects" asp-action="Create"
           class="btn newProject mt-3 mb-3">New Project</a>
    </li>

    @foreach (var project in Model)
    {
        <partial name="_ProjectCard" model="project" />

    }

</ul>